
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Anderson Niz\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("603x396")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 396,
    width = 603,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    603.0,
    396.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    499.0,
    351.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    162.0,
    37.0,
    image=image_image_2
)

canvas.create_rectangle(
    37.0,
    94.0,
    566.0,
    209.0,
    fill="#F5F5F5",
    outline="")

canvas.create_rectangle(
    37.0,
    74.0,
    566.0,
    94.0,
    fill="#F5F5F5",
    outline="")

canvas.create_rectangle(
    36.0,
    267.0,
    414.0,
    310.0,
    fill="#F5F5F5",
    outline="")

canvas.create_rectangle(
    37.0,
    217.0,
    566.0,
    258.0,
    fill="#F5F5F5",
    outline="")

canvas.create_text(
    42.0,
    272.0,
    anchor="nw",
    text="Salvar Lista Técnica E0 em:",
    fill="#363639",
    font=("KufamRoman SemiBold", 10 * -1)
)

canvas.create_text(
    42.0,
    220.0,
    anchor="nw",
    text="Consenso selecionado:",
    fill="#363639",
    font=("KufamRoman SemiBold", 10 * -1)
)

canvas.create_text(
    42.0,
    80.0,
    anchor="nw",
    text="Formulários selecionados:",
    fill="#363639",
    font=("KufamRoman SemiBold", 12 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=425.0,
    y=270.0,
    width=137.0,
    height=37.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=541.0,
    y=219.0,
    width=16.0,
    height=16.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=536.0,
    y=77.0,
    width=22.0,
    height=22.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=391.0,
    y=270.0,
    width=16.0,
    height=17.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=520.0,
    y=218.0,
    width=16.0,
    height=17.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=510.0,
    y=75.0,
    width=21.0,
    height=23.0
)
window.resizable(False, False)
window.mainloop()
